name: CI

on:
  push:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and Push to Humanitec
      uses: humanitec/build-push-to-humanitec@v1
      with:
        humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
        organization: chris-test-org
